//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigalev_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int id_phone { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string colour { get; set; }
        public double price { get; set; }
        public string image { get; set; }
    }
}
